name: catat_kendaraan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.3.4 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  get: 4.6.6
  firebase_auth: 4.19.5
  cloud_firestore: 4.17.3
  shared_preferences: 2.2.3
  intl: 0.19.0
  cached_network_image: 3.3.1
  youtube_player_iframe: 5.1.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_gen: ^5.3.2
  flutter_gen_runner: ^5.3.2
  build_runner: ^2.4.7
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter_gen: 
  output: lib/app/core/assets/
  integrations: 
    flutter_svg: true

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

